//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.18 at 10:39:16 AM EEST 
//

package com.currency.server.pojo.jaxb.eurofxref;

import lombok.Data;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import com.currency.server.utils.XmlDateAdapter;

/**
 * <p>
 * Java class for CurrencyExchangeTimeAndRates complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="CurrencyExchangeTimeAndRates"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Cube" type="{http://www.ecb.int/vocabulary/2002-08-01/eurofxref}CurrencyExchangeRate" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="time" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CurrencyExchangeTimeAndRates", propOrder = {"cube"})
@Data
@Entity
@EntityListeners(AuditingEntityListener.class)
public class CurrencyExchangeTimeAndRates {

    @XmlElement(name = "Cube")
    @OneToMany(
           mappedBy = "parent",
            fetch = FetchType.EAGER,
            cascade = CascadeType.ALL,
            orphanRemoval = true)
    protected List<CurrencyExchangeRate> exchangeRates;

    @Id
    @XmlAttribute(name = "time")
    @XmlSchemaType(name = "date")
    @Temporal(TemporalType.DATE)
    @Column(unique = true, nullable = false, updatable = false)
    @XmlJavaTypeAdapter(XmlDateAdapter.class)
    protected Date time;

    public void setupParentField() {
        if (exchangeRates != null) {
            for (CurrencyExchangeRate item : exchangeRates) {
                item.setParent(this);
            }
        }
    }

    /**
     * Gets the value of the cube property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cube property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getCube().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CurrencyExchangeRate }
     */
    public List<CurrencyExchangeRate> getExchangeRates() {
        if (exchangeRates == null) {
            exchangeRates = new ArrayList<>();
        }
        return this.exchangeRates;
    }

}